project:
  title: "Formula 1 time-rank duality"
  type: website
  output-dir: docs



bibliography: bibliography.bib
csl: elsevier-with-titles.csl


website:
  
  favicon: favicon.png
  search: 
    location: navbar
    type: overlay
  navbar:
    search: false
    pinned: false
    background: black
    foreground: "#E8E8E8"
  sidebar: false
  page-footer:
    center: 
      - text: "Link to paper"
        href: https://doi.org/10.48550/arXiv.2312.14637
      - text: "Contact" 
        href: https://www.silviofanzon.com/contact

format:
  html:
    toc: true
    toc-title: On this page
    toc-location: right
    code-overflow: wrap
    execute:
      freeze: auto
    theme:
      light: [flatly, theme-custom-light.scss]
      dark: [darkly, theme-custom-dark.scss]
    fig-align: center
    fig-cap-location: bottom
    link-external-icon: true



